### ISSUE TITLE
Cert Manager instructions not working

### ISSUE THREAD

**Issue by slipsibm** [mq-modernization-demo/mq01-ops#1]
In the Certificate Manager Section -> https://github.com/mqorg-slipsibm/mq01-ops#certificate-manager, it says to execute:
`oc apply -f setup/cert-manager-operator-sub.yaml`

This filename isn't in the setup directory. There is a file called `cert-manager-sub.yaml`. I tried executing that instead and get an error:

`[admin@bastion mq01-ops]$ oc apply -f setup/cert-manager-sub.yaml
Error from server (NotFound): error when creating "setup/cert-manager-sub.yaml": namespaces "cert-manager-operator" not found`

I can install the openshift cert manager from the Openshift web console.

**Comment by ODOWDAIBM** [comment]
Fixed with Operator Groups etc etc.  All tested and works nicely now!
